version: '3.3'
services:
  fury:
    container_name: fury_node
    image: fury/fury:mainnet-alpine
    working_dir: /workspace
    tty: true
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
    cap_add:
      - SYS_PTRACE
    env_file: 
      - fury.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace