version: '3.3'
services:
  fury:
    container_name: fury_node
    image: furychain/foundation-fury:0.41.2-alpine-prod
    working_dir: /workspace
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
      - 9090:9090
    cap_add:
      - SYS_PTRACE
    env_file:
      - fury.env
    volumes:
      - ./:/workspace
      - furyvisor:/root/furyvisor

volumes:
  furyvisor: null
